### ISSUE TITLE
Multiband COSMOS real galaxies

### ISSUE THREAD

**Issue by mpaillassa** [LSSTDESC/BlendingToolKit#118]
I open this issue to discuss how to make multiband COSMOS real galaxies.
For now what we would like is having properly normalized galaxy fluxes in each passband. After some discussions, several ideas have come out:
- Generating multiband parametric galaxy images with galsim and scaling the real galaxy images to these fluxes.
- Using Sersic fitting information from the galsim COSMOS catalog like `FIT_DVC_BTT`: bulge-to-total flux ratio (B/T) for the 2-component BULGEFIT.
- Using SED derived from the COSMOS 30-band photo-z catalog.

Maybe @rmjarvis @jmeyers314 @rmandelb would also have other ideas on this and may be interested to have such a feature directly within galsim ?

**Comment by HironaoMiyatake** [comment]
I taked to Atsushi Nishizawa. He told me that another possibility is to use [EL-COSMOS](https://arxiv.org/abs/2003.06394). They already have SEDs for each object, so we do not have to reproduce SEDs from the COSMOS 30-band photo-z catalog. I am not sure if they focus only on emission line galaxies, though. They say they have about 500k galaxies, so they may have red galaxies as well.

**Comment by ismael-mendoza** [comment]
Closed by #168
