### ISSUE TITLE
Support for "true" multiband catalogs and image generation

### ISSUE THREAD

**Issue by thuiop** [LSSTDESC/BlendingToolKit#122]
Right now we only have one truly multiband catalog, the Catsim one ; for COSMOS and galsim_hub we decided to only ensure correct fluxes in multiple bands. However, we may in the future want to support catalogs containing actual images in several bands ; I am working on extending galsim_hub for multiband images too. 
We will need to come up with a plan to deal with this : should we only support the actual bands in which images are generated ? Should we try to find the right flux and then use the "most relevant band" and rescale it ? 
This issue is not an urgent one but may become important in the future.

**Comment by ismael-mendoza** [comment]
deprecated
