### ISSUE TITLE
`dim_order` possible simplification

### ISSUE THREAD

**Issue by aboucaud** [LSSTDESC/BlendingToolKit#133]
In BTK at several places, one needs to know where the channels are last or not.
This is done through the `dim_order` keyword, that takes as input either "NCHW" or "NHWC".

I'm old enough to recall that issue existed in the early days of `tensorflow` because the default ordering had changed from the one used in `theano`, one of TF precursors.
They solved it by adding a boolean keyword called `channels_last`. 

IMHO we should use that convention as well, because
1. it spells easily and no one has to refer to the doc to understand its meaning
2. the boolean nature makes it very appropriate for the binary choice it does.

The only reason not to switch would be if you guys had in mind a third or more possibility of ordering the data.

**Comment by thuiop** [comment]
Well actually the current syntax comes from tensorflow, which is not very uniform on its variable names https://www.tensorflow.org/api_docs/python/tf/nn/conv2d
They also have the convention where the value is a string 'channels_first' or 'channels_last'.

**Comment by aboucaud** [comment]
Indeed I was wrong on the TF implementation. For my excuse I said I was old 😄 .

Still, I do think a boolean would be more convenient for that matter, because it is typo safe.
What do you think of that ?

**Comment by ismael-mendoza** [comment]
I like the idea of a boolean because there is only two options really. So I string just makes more space for errors.
