### ISSUE TITLE
galsim_hub test is broken

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#135]
There appears to be a problem with `galsim_hub` that is causing the test to break. I deactivated it for now so that we can continue to merge PRs but it would be good to look into this soon. 

Here is what I think is the main part of the error:

```
E       OSError: https://github.com/McWilliamsCenter/galsim_hub/blob/master/hub/Lanusse2020/model.tar.gz?raw=true does not appear to be a valid module.
404
```

**Comment by EiffL** [comment]
Thanks @ismael-mendoza and @thuiop for flagging this! I'm on it

**Comment by EiffL** [comment]
Ok, I found the problem, the free git-lfs storage of the `McWilliamsCenter` organization has ran out of bandwidth for the month (I'll notify @rmandelb here as well as this kind of issues may impact other CMU projects as well).

![image](https://user-images.githubusercontent.com/861591/115956467-1ae79d80-a4fd-11eb-987b-4ff3ff60ca52.png)

It will reset in 3 days, at which point I suspect it will work again. I suspect the BTK toolkit tests used most of this month's bandwidth, I don't think we had this problem before ^^' 

So, probably means I need to find a better way to store models, I'm gonna try to see if I can store them on zenodo instead.

**Comment by thuiop** [comment]
This would make sense. It may be better to disable the test regarding galsim_hub permanently, we do not want to be overusing the bandwidth just to make sure the test runs correctly !

**Comment by ismael-mendoza** [comment]
Yes! perhaps we could save the model inside the BTK repo? or deactivate the test and just have it run in a jupyter notebook for the documentation (will only run on merging which would reduce the times it runs by a lot)

**Comment by aboucaud** [comment]
> This would make sense. It may be better to disable the test regarding galsim_hub permanently, we do not want to be overusing the bandwidth just to make sure the test runs correctly !

Not permanently, but not run on every PR. If we individualize that test, we could configure the CI to run once a week on `main`. I guess it's plenty enough.

**Comment by ismael-mendoza** [comment]
deprecated
