### ISSUE TITLE
Improve time to generate images

### ISSUE THREAD

**Issue by sowmyakth** [LSSTDESC/BlendingToolKit#15]
At present script takes around 1 second to generate 120x120 6 band image of galaxy blend with isolated objects(6 band each) and PSF image. This isn't suffiecient for running large analysis. Possible solutions could be multithreading, parallelizing some code, caching images.

**Comment by ismael2395** [comment]
Cleaning up issues today. This one is an old issue and last time @sowmyakth mentioned that this wasn't a problem after she switched away from sherlock. If it does I'll reopen it
