### ISSUE TITLE
Do we need both `meas_bands` in DrawBlendGenerator and `meas_band_num` in MetricsGenerator?

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#152]
They seem redundant, also I think we need the one in the metrics to be a tuple as well ? (in the case of multiple surveys?)

**Comment by thuiop** [comment]
I was wondering the same thing. We need to get it straight at some point ; we should check where it is used exactly. Right now it is not used in the measurement part for instance, which is a bit paradoxical. I will create a broader issue to address all those inconsistencies in input/output.
