### ISSUE TITLE
`advanced-features` and other notebooks in Documentation?

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#165]
@thuiop what do you think? Should we add the notebooks besides `intro.ipynb` to the documentation eventually? Probably not urgent just wanted to post this issue in case we wanted to do it later

**Comment by thuiop** [comment]
I don't know if this is really useful ? I mean, we can do it if you think this is better, it will not take very long. We should probably make several pages though.

**Comment by ismael-mendoza** [comment]
Thanks @thuiop - my only concern is that this notebooks might become outdated and we never know? If there is a better way to make sure the notebooks are up to date I'm open to that definitely

**Comment by ismael-mendoza** [comment]
I wonder if there is a way to run a notebook in the CI and exit with an error if that fails? Maybe we can convert notebooks to `.py` (I've seen packages to do that), and then run them normally?
