### ISSUE TITLE
Add SNR as a metric

### ISSUE THREAD

**Issue by thuiop** [LSSTDESC/BlendingToolKit#171]
It could be interesting to add the signal to noise ratio as a metric for galaxies ; however this is not completely trivial as we do not draw the isolated galaxies with the noise.

**Comment by ismael-mendoza** [comment]
What equation/procedure were you thinking of using to estimate it ?

**Comment by thuiop** [comment]
I had in mind the equation 7 of this paper https://arxiv.org/pdf/2005.12039.pdf

**Comment by ismael-mendoza** [comment]
added in #412
