### ISSUE TITLE
numpy warning from pytest

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#185]
```
tests/test_draw.py::TestBasicDraw::test_default
  /home/imendoza/miniconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)
```

**Comment by thuiop** [comment]
This warning is from Cython, it has been around for a long time and is harmless ; numpy normally filters those warnings but pytest may be interfering with that. Long story short we should not worry about those in BTK. See here for more details https://github.com/numpy/numpy/issues/11788.
