### ISSUE TITLE
scarlet notebook fails (only sometimes) with nbval 

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#195]
seems like a stochatic issue, should investigate after the meeting

**Comment by thuiop** [comment]
Yes, I know it fails sometimes but I do not know why.

**Comment by ismael-mendoza** [comment]
I disabled it for now, also is there a way to make the scarlet notebook run faster? (It usually takes like a min)

**Comment by aboucaud** [comment]
What does the traceback say ?

**Comment by ismael-mendoza** [comment]
@thuiop and I suspect that we found the issue as we were working in the tutorial :) - @thuiop could you go ahead and add this fix to hopefully close the issue ? Or do you think there is some other problem?

**Comment by thuiop** [comment]
Yes I can do it.
