### ISSUE TITLE
Define the image generation API

### ISSUE THREAD

**Issue by xuod** [LSSTDESC/BlendingToolKit#2]
API developed during Hack Day at CMU:

- `btk.get_input_catalog` creates an astropy table containing properties of single galaxies (bulge+disk+AGN).
- `btk.create_blend_generator` creates a generator of lists of blends. Blends are lists of objects (position + properties) within a single post stamp image.
- `btk.create_obscond_generator` creates a generator of observing conditons. This contains the PSF, exposure time, survey filters, rotations of the field.
- `btk.draw_blends` generates the images using GalSim (blend + list of components images).
- `btk.metrics` implements a bunch of metrics to assess the performance of different algorithms.

Parts of these tasks are already implemented in the [WeakLensingDeblending](https://github.com/LSSTDESC/WeakLensingDeblending) and simply need some re-organization to provide a flexible training sample generator, fast enough to run on the fly. 

![image](https://user-images.githubusercontent.com/9870063/43339842-7ae08208-91a8-11e8-828e-b7e3fa8e7ab3.png)
![image](https://user-images.githubusercontent.com/9870063/43339846-7f22e3ce-91a8-11e8-9501-0e34e8e68b42.png)

**Comment by sowmyakth** [comment]
Implemented in [#8](https://github.com/LSSTDESC/BlendingToolKit/pull/8)
