### ISSUE TITLE
revert Rubin -> LSST Survey

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#209]
The survey is still called LSST not Rubin (that's the observatory)

**Comment by thuiop** [comment]
Yes but all the other surveys are also named based on the telescope and not on the survey itself... I don't think it makes a big difference, there is no room for confusion here.

**Comment by ismael-mendoza** [comment]
Yeah that's also a good point, I agree there is no room for confusion and it's good to be consistent.
