### ISSUE TITLE
Run Galsim_Hub model in tensorflow 2.0

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#224]
It appears that having tensorflow 1.0 as a dependency keeps giving us security warnings and comes with other problems (like compatibility with other newer packages). It would be nice if we could migrate the galsim_hub model to tensorflow 2.0 somehow - I think @aboucaud , @thuiop  had some ideas?

**Comment by aboucaud** [comment]
I'll propose something indeed.

**Comment by ismael-mendoza** [comment]
Deprecated for a while, please feel free to repoen if this becomes of interest again
