### ISSUE TITLE
Include metrics for segmentation algorithm

### ISSUE THREAD

**Issue by sowmyakth** [LSSTDESC/BlendingToolKit#26]
Add script that computes Intersection over Union (IoU) for the segmentation map produced by an algorithm. Estimating the segmentation map should be done in `measure` and IoU computation in `compute_metrics`.

**Comment by ismael2395** [comment]
An example of a segmentation map can be found in the last example of this notebook: https://github.com/LSSTDESC/BlendingToolKit/blob/master/notebooks/run_basic.ipynb

**Comment by thuiop** [comment]
Implemented in #125
