### ISSUE TITLE
Handle notebook metadata

### ISSUE THREAD

**Issue by b-biswas** [LSSTDESC/BlendingToolKit#262]
Is there a way to automatically manage the notebook metadata so that CI can also run smoothly?

**Comment by ismael-mendoza** [comment]
Hi @b-biswas thanks for creating this issue. Could you be a bit more specific on what problem you are having?

**Comment by ismael-mendoza** [comment]
One option which I'm not sure if it is what you had in mind is to use `nbstripout` in the pre-commit. We could set it so that it only strips out meta-data and not the output of each cell. 

https://github.com/kynan/nbstripout

**Comment by b-biswas** [comment]
Hi @ismael-mendoza, In my previous PR I was facing an issue when uploading the notebooks because my notebook kernel has a different name. 
@aboucaud proposed something quite similar ([https://github.com/datarootsio/databooks](https://github.com/datarootsio/databooks)
available in [https://pre-commit.com/hooks.html](https://pre-commit.com/hooks.html))  to nbstripout to remove the metadata. 

But if we completely remove the metadata won't it be a problem to run the CI?

**Comment by ismael-mendoza** [comment]
I think it should be OK - let me try it out in a PR
