### ISSUE TITLE
Tests on Python 3.8 time out when merged to main branch

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#265]
This is a very mysterious error. I noticed that in the CI the python 3.8 tests time-out, when re-running I think it goes away but I already observed it twice so I think there is a deeper bug at play. 

@aboucaud or @thuiop have you ever seen this happen in other contexts? Do you know of any solutions?

<img width="939" alt="Screen Shot 2022-02-20 at 8 03 23 PM" src="https://user-images.githubusercontent.com/11745764/154873248-dfa80d9c-3106-40e2-b818-dbdf272e3f70.png">

**Comment by thuiop** [comment]
Very intriguing. I have never seen that, and I have no idea where it comes from.

**Comment by ismael-mendoza** [comment]
Hmm didn't happen this last merge, I guess I'll keep monitoring it

**Comment by ismael-mendoza** [comment]
It happend again in my latest merge :'( so maybe we should investigate

**Comment by aboucaud** [comment]
Suggestion : using -vv in pytest options to maximize the verbosity and make sure we get as much feedback as possible

**Comment by ismael-mendoza** [comment]
Haven't seen this again in a while
