### ISSUE TITLE
lmfit dependency not listed in installation instructions

### ISSUE THREAD

**Issue by pmelchior** [LSSTDESC/BlendingToolKit#27]
The install of btk works fine, but then `lmfit` is required to run it, so adding these two options to the install instructions would help:

```
pip install lmfit
conda install -c conda-forge lmfit
```

**Comment by sowmyakth** [comment]
Requirement of lmfit is already mentioned in the README page and the docs installation [page](https://blendingtoolkit.readthedocs.io/en/latest/install.html). Do you have a suggested page to add it so as to make it more obvious?

**Comment by pmelchior** [comment]
Yeah, now that you say it... Both fitsio and lmfit are non-standard packages, so I guess that many people will find themselves searching for this information.

Two options come to my mind: Modifying `setup.py` to request all requirements (or complain otherwise) or adding install instructions to the installation page.

**Comment by ismael2395** [comment]
Suggestion in PR #29

**Comment by ismael2395** [comment]
Hi @pmelchior, we followed both of your suggestions in PR #29 , please let us know if you would suggest further actions and I can reopen the issue. Closing for now...

**Comment by pmelchior** [comment]
All good, thanks
