### ISSUE TITLE
Are we using AB magnitudes or classical magnitudes? 

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#279]
Concerning the fact the input mag seems to be an AB magnitude, is this a residual from the past or not. Because I though we had changed this and defaulted to classical magnitudes.

_Originally posted by @aboucaud in https://github.com/LSSTDESC/BlendingToolKit/pull/228#discussion_r829782223_

**Comment by ismael-mendoza** [comment]
Thanks @aboucaud I'm actually not sure if we ever changed the catalogs, we should look into this more and make sure we are consistent. 

Does anyone know @thuiop @mpaillassa ?

**Comment by mpaillassa** [comment]
I don't think we are using AB magnitudes because we use magnitudes as:
`mag = Z - 2.5*log10(flux)`
while in the AB magnitude system the flux is normalized with some reference.

**Comment by thuiop** [comment]
I am not so convinced. Magnitude is only defined relative to a zeropoint ; the question is which convention is used for the zeropoints we have, and for the values in the catalog. I believe that in WeakLensingDeblending they used AB magnitudes for their zeropoints and in the catalog, so the u_ab must still be an AB magnitude.

**Comment by mpaillassa** [comment]
Yes I am not so convinced neither and I think I see what you mean. 
If the AB magnitude convention comes back to have:
`mag_AB = Z_AB - 2.5log10(flux/ref_AB)`
And that our magnitudes are considered as:
`mag = Z - 2.5log10(flux)`
And that in practice we have set `Z = Z_AB + 2.5log10(ref_AB)`, then we are still having AB magnitudes ? (even though the calculations are a bit different)
Then AB magnitudes are more or less always used, but it is hidden in the experimental zeropoints ?

**Comment by mpaillassa** [comment]
By the way I found this [WLD issue](https://github.com/LSSTDESC/WeakLensingDeblending/issues/47) that is a bit more into flux computations, but that relates a bit to magnitude conventions.

**Comment by RobertLuptonTheGood** [comment]
Is there a reason not to use AB?  Rubin uses it consistently, as did SDSS, and I think it's definitely the way to go.  Or Jy of course (which is equivalent)

**Comment by mpaillassa** [comment]
> Thanks @mpaillassa and @thuiop does that mean that we updated the zeropoints to correspond to classical magnitudes but never the magnitudes in the BTK catalogs ? (is there a mismatch?)

The [zeropoint update](https://github.com/aboucaud/galcheat/issues/48) that we did was just to change the way we compute fluxes from magnitudes from the WLD computation:
* flux = Z_{24} * 10^(-0.4 * (mag-24))

to a more usual computation:
* flux = 10^(-0.4 * (mag-Z))

But we are still directly using the magnitudes from the catsim and the cosmos catalogs. We just changed the zeropoint values accordingly to compute the same fluxes with the second formula.

So if the magnitudes in the catsim and cosmos catalogs are AB magnitudes we are using AB magnitudes. Then the point for the image simulations is to have the right calibrated zeropoint to simulate the right fluxes from the magnitudes. Do you agree and is it a bit more clear ? @ismael-mendoza @thuiop @aboucaud @RobertLuptonTheGood

**Comment by thuiop** [comment]
I agree with you. I am pretty sure that the zeropoints we had in the first place were using the AB convention but I do not remember if they were changed at some point in BTK or galcheat.

**Comment by mpaillassa** [comment]
Yes apparently @ismael-mendoza found an inconsistency between WLD and Galcheat/BTK computed counts. This could be due to at least one of the following reasons:
* In the new Galcheat/BTK flux computation we removed the extinction.
* Even if the new Galcheat/BTK flux computation should be equivalent to that of WLD (appart from the aforementioned extinction), the Galcheat zeropoint values may not be perfectly equivalent to that of WLD because their computation involves the `effective_area` of the telescope and e.g., the LSST `obscuration` (and thus `effective_area`) was changed.

**Comment by ismael-mendoza** [comment]
Ok so it seems that from the meeting yesterday the zeropoints in galcheat are in ab so that since the magnitudes in btk are in ab also we should be all good. So I'm closing this issue. @aboucaud @mpaillassa please let me know if I missed anything.
