### ISSUE TITLE
Implement get_input_catalog

### ISSUE THREAD

**Issue by roucelle** [LSSTDESC/BlendingToolKit#3]
- input: cat name 
- typical output : astropy Table( 'id', 'ra','dec', bulge props with SED, disk props with SED, AGN props with SED)

This function creates an astropy table containing information that is useful to generate postage stamp images with appropriate distributions of shapes, colors, fluxes, etc. Typical input catalogs will be CatSim generated catalogs or the DC2 catalog, in which case this will use GCR.

**Comment by sowmyakth** [comment]
Implemented in [#8](https://github.com/LSSTDESC/BlendingToolKit/pull/8)
