### ISSUE TITLE
Setting `ref_mag` and documentation

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#336]
I have a couple of questions about `ref_mag` and how it is used and set. In particular, is it expected to already be in the catalog or do we always use `i_ab` for CATSIM. In that case, what happens with surveys without `i_ab` ? Can this ever be a problem?

In the COSMOS catalog we alway use the `ref_mag`  even when running it with the LSST survey. Why? 

Maybe we should add something to the documentation about it?

**Comment by thuiop** [comment]
The ref_mag currently serves two purposes :
- It can be used in sampling functions to make a magnitude cut, in a way which will work with any catalog ; it is also used in the interactive plotting to limit the magnitudes
- It is used by the COSMOS generator if you do not provide the magnitudes for every band (as is the case with the Galsim one). In that case, the same magnitude is assumed for every filter (and is the one from the ref_mag column)

For the i_ab, you are right ; we never ran into the issue as we only use the initial Catsim catalog which contains the column. We should add it as an optional parameter for the CatsimCatalog.

**Comment by ismael-mendoza** [comment]
Mention in `custom_tutorial` just one sentence on what it is
