### ISSUE TITLE
implement aperture photometry metric

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#342]
@aguinot  suggested a very interesting metric based on aperture photometry which alleviate some important biases and should be interesting for photo-z folks as well. The procedure is as follows: 

input: noisy postage stamp with (simulated) galaxy blend 
output: aperture photometry flux for each object in the blend (if all were detected)

- Run deblending algorithm on image to get light profile of each detected object 
- For each detected object, take input noisy image and subtract all other objects from the image based on deblended (noiseless) profiles
- Measure the flux of that object using SEP aperture photometry (this is a function takes in an input image, a centroid, and the size of the aperture)

Finally, in order to do a fair comparison: Don't compare with true input flux from the catalog, rather repeat same procedure but subtracting the true noiseless light profiles of each object.

This procedure is especially important in the multi-band setting. 

Another interesting comparison, to see how much deblending would help, would be to just run this procedure with no deblending. Just run the SEP function on the input image without subtracting sources. 

**Note:** A similar metric for measuring shapes would also be good to implement, I think.

**Comment by thuiop** [comment]
This kind of metrics is exactly what I envisioned for the "target_meas" parameters. Actually for the shape we already have the one for the ellipticities ; there are probably other measures we can make.

**Comment by ismael-mendoza** [comment]
It would be good to implement at least  one more `target_meas` which includes this aperture photometry as @aguinot suggested

**Comment by ismael-mendoza** [comment]
Documentation in SEP; the radius can be set to some multiple of the size of the PSF

https://sep.readthedocs.io/en/stable/apertures.html

**Comment by ismael-mendoza** [comment]
Implemented in #412 at least a basic version
