### ISSUE TITLE
make binder build faster

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#344]
Perhaps if we can somehow use a `requirements.txt` file instead of the `env.yaml` that might help. It continually takes too long for me

**Comment by aboucaud** [comment]
There are two ways of making binder build this faster:

1. you have a lot of users and Binder keeps the build docker image in its cache
2. you build your own Docker image of the repo (from time to time) which can be stored by GitHub, so Binder can use it without having to rebuild the image each time if the process is long.

**Comment by ismael-mendoza** [comment]
Resolved in #354
