### ISSUE TITLE
minimum number of galaxies

### ISSUE THREAD

**Issue by b-biswas** [LSSTDESC/BlendingToolKit#372]
Will it be a good feature to have a minimum number of galaxies in a blend along with the maximum number?
So we can keep a consistent galaxy density range useful for evaluating delbenders

**Comment by ismael-mendoza** [comment]
Hi @b-biswas - sure I don't see a reason not to include this extra flag. It should be a simple addition to the default sampling function. Feel free to open a PR and implement this or let us know if you have any questions. Thanks!
