### ISSUE TITLE
Implement create_blend_generator

### ISSUE THREAD

**Issue by roucelle** [LSSTDESC/BlendingToolKit#4]
- input : catalog, batch size, sampling strategy 
- output : generator.

The generator creates blend lists according to a given strategy. Proposed strategies include simple 
1. random choice and positioning on the post stamps of a given number of galaxies
2. using friends-of-friends implemented in DC2 to find close pairs.

**Comment by sowmyakth** [comment]
Implemented in [#8](https://github.com/LSSTDESC/BlendingToolKit/pull/8)
