### ISSUE TITLE
Turn instructions for releasing package into a script or ci action

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#414]
Suggestions welcome, instructions in `MAINTAINER.md`

https://github.com/LSSTDESC/BlendingToolKit/blob/main/MAINTAINER.md#making-new-releases

Resources: 

- https://www.jessesquires.com/blog/2022/03/26/gh-action-merge-release-to-main/

**Comment by aboucaud** [comment]
https://github.com/marketplace/actions/update-python-project-check-version-test-git-tag-github-release-deploy-to-pypi
