### ISSUE TITLE
photoutils as an additional algorithm

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#416]
Does anyone know about it? Is it any different than SExtractor? 

https://photutils.readthedocs.io/en/stable/index.html

**Comment by aboucaud** [comment]
Yep totally different story.
`SExtractor` has been developed mostly by a single devoted person (Maxime's PhD co-advisor) from 1996 till a few years back (for optimizations) and clearly you don't want to know what's inside :)  
`photutils` is a tool created by the astropy community to do similar tasks as SExtractor but Python-only (a bit of Cython) and with explicit methods. But it never managed to reach the audience and I've rarely seen a pipeline using only photutils (maybe JWST people now) except from specific functions.

**Comment by ismael-mendoza** [comment]
ok maybe not as relevant to us
