### ISSUE TITLE
AssertionError in drawing real galaxies with CosmosCatalog /CosmosGenerator

### ISSUE THREAD

**Issue by grantmerz** [LSSTDESC/BlendingToolKit#471]
Since there is some noise in the real galaxy catalogs, there are negative pixel values.  This raises the AssertionError here when trying to create a blend batch of real galaxies

https://github.com/LSSTDESC/BlendingToolKit/blob/0ff9166ffca1f30c5ded110e3e887aab31aa650f/btk/blend_batch.py#L39

**Comment by ismael-mendoza** [comment]
#482 fixes this @grantmerz let me know if you find any more issues
