### ISSUE TITLE
Implement observing conditions generator

### ISSUE THREAD

**Issue by roucelle** [LSSTDESC/BlendingToolKit#5]
create_observing_generator

- input : survey name (Possibility for the user to give a table of properties ?)
- output : generator

Creates a generator of characteristics of a given observation for a given survey.

generator outputs exposure time, PSF (fixed for now ?), filters, rotation of stamp. 

Could be adapted from WeakLensingDeblending.

**Comment by sowmyakth** [comment]
Implemented in [#14](https://github.com/LSSTDESC/BlendingToolKit/pull/14)
