### ISSUE TITLE
custom PSF and/or noise  ? 

### ISSUE THREAD

**Issue by roucelle** [LSSTDESC/BlendingToolKit#6]
- inputs : blends list, observing conditions 
- outputs : blended poststamp + single galaxies appearing in the blend ("truth" poststamps :-) ) 

caveats : 
- Noise to be added at this stage ? 
- All are PSF convolved ?

**Comment by sowmyakth** [comment]
Basic framework is Implemented in [#8](https://github.com/LSSTDESC/BlendingToolKit/pull/8). Noise addition and PSF convolution done. Script currently does not have option to cache images or augment images with different noise or PSF

**Comment by ismael2395** [comment]
I was thinking it would be nice for the user to define their own PSF they want to plug-in and not be constrained to the one in WeakLensingDeblending. Do you think this might be useful @sowmyakth ? 

For noise, I can imagine it might be cool to have custom SNR although not sure how this would work exactly for PoissonNoise

**Comment by sowmyakth** [comment]
@ismael2395 btk already has option for user defined psf and sky background parameters. Like example 5 in this [notebook](https://github.com/LSSTDESC/BlendingToolKit/blob/9e4f0d5fa175592ebd646e433fbc87bcdf9a0d46/notebooks/custom_sampling_function.ipynb). For a given batch, the different bands can have different observing conditions.  But those parameters are constant for a given batch. Implementing different observing conditions for blends within a batch would require modifications in `draw_blends` and `create_observing_generator`

**Comment by ismael2395** [comment]
As @sowmyakth said this is already implemented via WLD and the `create_observing_generator`, extensions might be possible with more complicated PSF models, etc. but  will open an updated issue in that case
