### ISSUE TITLE
Refactor the BTK module

### ISSUE THREAD

**Issue by aboucaud** [LSSTDESC/BlendingToolKit#70]
While sprinting on BTK, I have spotted various places in the code that could be refactored
- [x] **imports** – enforce absolute imports and reorder imports in files
- [x] **installation** – the installation procedure could be improved, maybe by updating the required dependencies or specifying different level of install (e.g. with or without `galsim`, ...)
- [x] **entry points** – the way to programmatically run BTK without running into too much details is through the `btk_input.py` which is currently outdated. This script should be incorporated into the module and be made available to the user upon install via as a command-line script through and `entry_point` in the `setup.py`
- [x] **documentation** – automate the generation of doc through CI

**Comment by ismael-mendoza** [comment]
all seem like good suggestions to me, thanks @aboucaud !

**Comment by ismael-mendoza** [comment]
Documentation will be taken care in #68

**Comment by ismael-mendoza** [comment]
entry points in #48

**Comment by ismael-mendoza** [comment]
any remaining issues with installation resolved in #104
