### ISSUE TITLE
Do we need to support catalog building in BTK

### ISSUE THREAD

**Issue by herjy** [LSSTDESC/BlendingToolKit#73]
At the moment BTK has functionalities to load a catalog and apply selection functions that restrict the the sample of galaxies use to generate patches. 
My question is: Do we need in BTK to support this functionality. While adapting a new format for drawing images (from the cosmos galsim images), I realised that the Catalog handling and the selection function were rather the responsibility of the user and I do not see the point for BTK to support this. BTK could very happily work if we were provided a catalog that is already filtered by any means the user deem necessary. 

Instead here, we go through the trouble of building an interface for applying selection function to catalogs, which requires some uniformisation and probably more steps for a user who wants to use a specific custom catalog than if these functionalities weren't there. Plus it imposes that we maintain a flexible interface. It is not a problem in itself, but it should be well motivated. 

This matter is open for debate and I'm happy to be showed what I might be missing.

**Comment by ismael-mendoza** [comment]
Thanks @herjy for posting. Tagging @aboucaud who might have an opinion about this.

**Comment by thuiop** [comment]
I'll just put there my opinion which I already evoked : I think that there may be some value for newcomers who do not know the Catsim (or COSMOS) catalog very much, but would still want to get some cuts in the catalog (say mag cuts), if we were to provide some default selection functions for the catalog we support ; this would need some extra effort though, and I agree that it may be of limited value.
Also, I note that the user can filter the catalog beforehand if he prefers right now.

**Comment by herjy** [comment]
The user can do it beforehand, but they still have to go through the BTK implementation of catalogs on top it because `BlendGenerator` expects a `btk.Catalog` object. I think users should always understand their catalogs. 
Nothing keeps us from providing a pre-made selection with an example catalog in the notebooks, but I'm not sure why we need to provide a BTK interface for it.

**Comment by thuiop** [comment]
I do not think the Catalog object is that heavy when dealing with Catsim or COSMOS though ? It could be created with `Catalog(catalog)` where `catalog` is the actual catalog object, which they may have filtered beforehand. I agree with you that users should ultimately understand their catalog enough to make the cut themselves, I was more thinking about users trying out BTK. But it is a very limited use case, I agree with that. I guess we could remove the selection function part ; I do think the Catalog object should be kept as it is useful (mainly for us), and I don't feel it is too much a weight for the user.

**Comment by aboucaud** [comment]
I'm not really opinionated about this.
On the one hand Rémy is right about the willingness to keep things as light as possible, and the `Catalog` object is not doing much.
On the other hand, as Thomas stated, I like to be able to quickly wrap a catalog as `Catalog(catalog)` and have it standardized for the rest of the analysis (we're probably not there yet with the current implementation though), just because I feel it is much more work to have to support various types of catalogs down the analysis. But I may well be wrong here because I have not yet explored much of the codebase.

**Comment by herjy** [comment]
I am not sure how useful the Catalog is to "the analysis". Sure it stores information about the galaxies, but this is dependent on the tool used to generate it. For cosmos galaxies or ML models, the catalogs are not that relevant and its entries might differ so widely that uniformisation willl be problematic. Even if you look at magnitudes, one of the problems I have right now is: we use a certain predicament for selecting galaxies with a given mag, but when building say a Rubin observation from an HST catalog, how useful is the information that the galaxy has mag 22 in f814w and what does it mean for Rubin's y-band for instance? Given that these models are noiseless we can actually give them the magnitudes we want in the images.

This means that when we generate the images we need to record the magnitudes we've put in, but not the ones we received as entries in the initial catalog.

**Comment by herjy** [comment]
Actually, I'm the same as you Alexandre, on how useful the catalogs are in the analysis (i.e. i.d.k). I'll need to dig further before we decide anything on this.
