### ISSUE TITLE
Correct shifts and magnitudes for galsim galaxies

### ISSUE THREAD

**Issue by herjy** [LSSTDESC/BlendingToolKit#80]
Following PR #52  the shifts and fluxes of galaxies generated with cosmos are  not handeled. This requires writing the proper code for `draw_single` and check how this interfaces with the `draw_blend`. To do imminently.

**Comment by mpaillassa** [comment]
It seems that for now galaxy images generated with cosmos are scaled to unit flux and are not shifted. 
Have you already a precise idea on how to do it ? We may want to use `galsim.GSObject.withFlux()` and `galsim.GSObject.shift()` but we need to define how to generate the flux and shift offset values (we may also want to record them ?).

**Comment by thuiop** [comment]
What I was talking about in the meeting : in the image generation code we had, there are `galsim.Bandpass` objects (which are instantiated from specific files containing the throughput for each wavelength for a particular survey. Those are used like `gal.drawImage(bandpass,image=im)` where `gal` is a GSObject (obtained by convolving the galaxy with the PSF). Before convolving the galaxy, we also multiply it by some coefficient (the same for all filters) and the number of exposures ; I have the calculation for the said coefficient, but I am not sure which value corresponds to what exactly, so the whole thing is a bit mysterious to me. 
I am not familiar with Galsim internals so I do not know if this is really relevant but it may be interesting if we want to get realistic fluxes.
