### ISSUE TITLE
Add DC2-like images

### ISSUE THREAD

**Issue by BastienArcelin** [LSSTDESC/BlendingToolKit#81]
Following the discussion at the beginning of the sprint week, we think it could be interesting to generate DC2-like images.  François mentioned that it might be easier to generate those from `GalSim ` instead of going through the butler since DC2-images are initially generated with this package. Here is what I think about the two options:

- Generated images with `GalSim` might be easier as we have already morphology and color parameters from the DC2 extragalactic catalogs. However, we might lack complexity, at least in PSF models for example.

- Going through the butler to generated stamps is not very difficult but requires a bit of time to match observed and extragalactic catalogs if we want to access "truth" properties of observed objects. Moreover if we want images of noiseless isolated galaxies we need to generate them using `GalSim` and information from the extragalactic catalog...

We probably need to brainstorm a bit more about this to go further.

**Comment by ismael-mendoza** [comment]
deprecated
