### ISSUE TITLE
Various issues related to new Survey/Catalog objects

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#82]
- [ ] Check whether a given survey is appropriate for a catalog (potentially can be added in DrawBlendsGenerator as a class attribute)

- [ ] check certain mandatory column names are present in the given catalog and fail with a nice exception if they are not

- [x] make all the `sigma_X` immutable containers rather than numpy_arrays (in `obs_conditions.py`). Although then you can't multiple them so you would need to convert them to np arrays later. 

- [x] Maybe create some `Filter` object for each Survey or something else that accounts for this functionality. @aboucaud  and @herjy had some discussion: 

> why not also define a Filter or Bandpass the same way you define a Survey, with its associated psf_scale, mean_sky_level, exp_time and zero_point ?

> I'm rolling back on the Filter objects. We will have to make distinction between the g band from HSC and the g band from Rubin for instance and that will lead to the creation of a lot of objects. Maybe there is a right way to do this, but I suggest to put it in a different PR then.

- [ ] Question: Do we need `CosmosCatalog` at all or all these Catalog objects? Related comments

> Sadely for galsim yes, there are two catalogs that contain slighlty different informations. Though we were thinking of sort of dropping the galsim catalog. It is not actually necessary at this point and we could use the default catalog to draw coordinates and fluxes as it was done before. Galsim cats only matter for the draw single part. But my opinion of catalog is shifting, and I actually don't think that we need to build a CosmosCatalog here, at least, not unless we want to draw HST images. If we want to generate Rubin images, we should rather use the WLD catalog. To generate Rubin images, you actually want a Rubin-compatible catalog with the magnitudes in the Rubin bands, that's what matters.

**Comment by herjy** [comment]
One comment that, I think, addresses a few questions is that I'm not sure we need the Cosmos catalog as a BTK catalog object. We only need it to generate images of individual galaxies, but we could still use other catalogs to generate a blend parameters. I'll try that in my next PR.
