### ISSUE TITLE
Fix  COSMOS catalog + add unit tests

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BlendingToolKit#91]
In #87 the COSMOS galaxy catalog was removed from the `__init__` of the `CosmosGenerator`. I think it should be directly included in the `self.catalog`. To do imminently after closing #87

**Comment by mpaillassa** [comment]
I am willing to solve this issue but I don't fully understand the current state of COSMOS catalogs and what you mean. 
The `render_single` current code in the `CosmosGenerator` seems a bit deprecated as `len(self.catalog)` fails and `catalog.makeGalaxy` does not exist anymore. Should we have a similar function to `get_catsim_galaxy` for COSMOS ?

**Comment by thuiop** [comment]
I think the problem is 
1. the catalog object is not well managed. There is a galsim object called COSMOSCatalog which is the one with the makeGalaxy method, and for some reason when we rewrote a part of  BTK it got lost somewhere. My belief is that it should be stored in our Catalog object, as the field _raw_catalog, which can be accessed with the corresponding get method, and which does not have much purpose now. (this was never propery done I think)
2. The fluxes for the galaxies are wrong, which is issue #80 . Also, the function does not use the "entry" argument as it should.

**Comment by ismael-mendoza** [comment]
Hi @mpaillassa, thanks for looking into this and sorry about the confusion. This issue was more of a "note to self" since I wrote it before you were going to work on this. I don't think we ever figure out exactly a good way to approach this so we are definitely open to ideas on how to structure the COSMOS object generation. 

That being said, @thuiop is entirely correct on what seems to be current the easiest approach. Regarding `1.` it seems sensible to store the actual `COSMOSCatalog` object from galsim as a `_raw_catalog` and access it later when rendering (calling the makeGalaxy method to get the corresponding galsim object). Currently it seems like it's asking for two files as a list, but it's not clear to me what are these two files or what @herjy intended. Also the current `_raw_catalog` stored is just a copy of the astropy table before the processing in `_prepare_table`. 

Another thing, I like the idea of standardizing the format of the astropy table (the `self.table` attribute) in `_prepare_table` as @herjy has suggested via `btk_size`, `btk_index`, `ref_mag`, etc. Although I don't think they have been consistently propagated and you can feel free to change this as needed. 

In terms of the fluxes, I'm not sure what is the best way to handle this. @herjy was proposing to use the catsim catalog to get fluxes for these galaxies in all bands (it seems the cosmos catalog only contains 1 band, but we could start with that for now). 

Finally, when @thuiop said that the "entry" attribute is not used, I just wanted to elaborate that currently the `render_single` draws a random cosmos galaxy without any reference to the `btk_index` field in `entry`, but it should use it. Also, we want to use the correct PSF stored in the filter. 

Hopefully this makes more sense now, but feel free to ping me in slack if you have any other questions.

**Comment by mpaillassa** [comment]
Thank you for your answers. I think I see the situation better now. And when looking back at the code when simulations with Cosmos galaxies were working, I realize that there is indeed no link between the galsim `COSMOSCatalog` and the BTK `CosmosCatalog`. I have started a PR about these Cosmos catalog issues.
