### ISSUE TITLE
Add lensing shear to blends

### ISSUE THREAD

**Issue by HironaoMiyatake** [LSSTDESC/BlendingToolKit#98]
We want functionality to add lensing shear to blends. We can make use of GalSim implementation. Based on our discussion in our BTK telecon, we need to take care of following things.
- Lensing shear needs to be added for each object, since shear is different for sources at difference redshift. We could specify shear for each object in an input catalog. In this way, people could add, e.g., in a simplest case a constant shear or in a complicated case variable shear computed from N-body simulations.
- We might want to check with Matt Becker things like astrometric shift due to lensing.

**Comment by thuiop** [comment]
Note on how it could be done  : 
- Modify the render_single function to add a gal.shear() 
- Have a custom sampling function which adds a shear column to the entries corresponding to a blend. I think this can be done in the default sampling function, at least when considering constant shear, and adding a "shear" argument to the __init__ (defaulting to 0). If people want a more complex shear distribution with different shear for each object they are better off writing a new sampling function anyway.

**Comment by aboucaud** [comment]
@aguinot we just discussed about this issue at the BTK telecon. 
Do you have an opinion on how you would proceed with this ?

**Comment by aguinot** [comment]
I guess a constant shear should be "easy" to implement. BUT, we have to take into account the way those simulations are going to be used. For example if people are interested in measuring the shear bias they might want the same object (including the same noise realization!) with different shears (e.g. +g/-g). 
I guess that having the possibility to have a different shear for all the objects in a blend is interesting as well but I have no idea of what to do if I had this information at the moment.
Regarding having a realistic distribution of shear, I am not sure that should be an high priority. This usually done on simulations coming from an N-body like DC2. If you are looking only at independent postage stamps, I am not sure that you really care about having a varying shear.
Also, if we see BTK as a tool to test codes and help the development of them, it is preferable to have a controlled environment, i.e. a constant shear.

I would recommend to discuss with other lensing people. There is probably some needs in the community that I didn't thought about. As mentioned above, Matt Becker or Erin Sheldon are probably the right people to talk to.
Hope this help.
